version: "3"
services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    restart: always
    ports:
        - "5432:5432"
    networks:
      - database
    env_file: .env
    environment:
        POSTGRES_USER: "${POSTGRES_USER}"
        POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        POSTGRES_DB: "${POSTGRES_DB}"
        TZ: "Asia/Seoul"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  # back:
  #   build:
  #     context: ./back
  #     dockerfile: Dockerfile
  #   container_name: back
  #   restart: always
  #   ports:
  #     - 3095:3095
  #   depends_on:
  #     - postgresql
  #   networks:
  #     - database
  #     - frontApp
  # front:
  #   build:
  #     context: ./test
  #     dockerfile: Dockerfile
  #   container_name: front
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - back
  #   networks:
  #     - frontApp

volumes:
  postgresql:

networks:
  database:
    driver: bridge
  frontApp:
    driver: bridge
